# Site settings
title: "Itinerary: Interactive Maps and Timelines Based on Historical Literature"
email: mjr@clearbold.com
description: ""
baseurl: ""
url: "https://clearbold.com/itinerary"
twitter_username:
github_username:  clearbold

# Where things are
destination:      ./_site
# source:           ./_source


# Handling Reading
exclude:          ["templates", "Gemfile", "Gemfile.lock", "README.md", ".gitignore"]

# Conversion
markdown: kramdown

# Compensating for gh-pages project site
baseurl: /itinerary
# https://github.com/jekyll/jekyll/issues/332

asset_url: https://hofstra.github.io/design-framework
